version: "3.8"

services:
  nginx:
    image: "${APP_NAME}-nginx"
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    depends_on:
      - app

  app:
    image: "${APP_NAME}-app"
    build:
      context: .
      dockerfile: docker/php/Dockerfile